---
name: Build
on:
  push:
    branches: [master]
    
jobs:
  component-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to the Kubernetes Cluster
        run: | 
          mkdir -p ${HOME}/.kube
          echo "$CONFIG" > /home/runner/.kube/config
          chmod +x /home/runner/.kube/config
          aws --version
        env:
          CONFIG: ${{ secrets.config }}
          
#       - name: Setting up kubeconfig ENV for Github Chaos Action
#         run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
#         env:
#           ACTIONS_ALLOW_UNSECURE_COMMANDS: true          
        
          
#       - name: Get nodes of the cluster
#         env: 
#           KUBECONFIG: /home/runner/.kube/config
#         run: kubectl get nodes
        
        
