---
name: Build
on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
    
jobs:
  component-pipeline:
    runs-on: self-hosted
    steps:
      - name: Getting the nodes
        run: |
          ls
          pwd
          whoami
          kubectl get nodes
          sleep 50

  component-pipeline-2:
    runs-on: self-hosted
    steps:
      - name: Getting the nodes
        run: |
          ls
          pwd
          whoami
          kubectl get nodes
          sleep 50
