---
name: Build
on:
  push:
    branches: [master]
    
jobs:
  component-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to the Kubernetes Cluster
        run: | 
          mkdir -p ${HOME}/.kube
          echo "$CONFIG" > ${HOME}/.kube/config
          echo "$CONFIG"
        env:
          CONFIG: ${{ secrets.config }}
        
          
      - name: Get nodes of the cluster
        env: 
          KUBECONFIG: /home/runner/.kube/config
        run: kubectl get nodes
        
        
