---
name: Build
on:
  push:
    branches: [master]
    
jobs:
  component-pipeline:
    runs-on: ubuntu-latest
    steps:
#       - name: Connect to the Kubernetes Cluster
#         run: | 
#           echo "$CONFIG" > /home/runner/.kube/config
#         env:
#           CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
#           ADMIN_CONFIG: ${{ secrets.ADMIN_CONFIG }}
          
      - name: Getting kube config
        env:
          KUBECONFIG: config
        run: |
          echo "${{ secrets.PRIVATE_INSTANCE_KEY }}" > private-key
          ssh -i "udit-litmus-e2e.pem" ubuntu@ec2-54-67-4-114.us-west-1.compute.amazonaws.com
          kubectl get nodes
          
#       - name: Setting up kubeconfig ENV for Github Chaos Action
#         run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
#         env:
#           ACTIONS_ALLOW_UNSECURE_COMMANDS: true          
        
          
#       - name: Get nodes of the cluster
#         env:
#           KUBECONFIG: ${{ secrets.KUBE_CONFIG_DATA }}      
#         run: kubectl get nodes
        
        
