---
name: Build
on:
  push:
    branches: [master]
    
jobs:
  component-pipeline:
    runs-on: ubuntu-latest
    steps:
#       - name: Connect to the Kubernetes Cluster
#         run: | 
#           echo "$CONFIG" > /home/runner/.kube/config
#         env:
#           CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
#           ADMIN_CONFIG: ${{ secrets.ADMIN_CONFIG }}
          
      - name: Getting kube config
        env:
          KUBECONFIG: config
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > config
          kubectl get nodes
          
#       - name: Setting up kubeconfig ENV for Github Chaos Action
#         run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
#         env:
#           ACTIONS_ALLOW_UNSECURE_COMMANDS: true          
        
          
      - name: Get nodes of the cluster
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG_DATA }}      
        run: kubectl get nodes
        
        
