---
name: Build
on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
    
jobs:
  component-pipeline:
    container: 
      image: litmuschaos/litmus-e2e:ci
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /etc/kubernetes:/etc/kubernetes
        
    runs-on: self-hosted
    steps:
      - name: Getting the nodes
        env:
          KUBECONFIG: /root/.kube/config
        run: |
          kubectl get nodes
          go
          

#   component-pipeline-2:
#     runs-on: self-hosted
#     steps:
#       - name: Getting the nodes
#         run: |
#           ls
#           pwd
#           whoami
#           kubectl get nodes
#           sleep 50
