---
name: Component-Pipeline
on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
    
jobs:
  Setup_Litmus_Infra:
    container: 
      image: litmuschaos/litmus-e2e:ci
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /etc/kubernetes:/etc/kubernetes
    runs-on: self-hosted
    steps:
      - name: Litmus Infra Setup In Cluster-1
        env:
          KUBECONFIG: /root/.kube/config
        run: ls
        
  Setup_App_Deployment:
    needs:  Setup_Litmus_Infra
    container: 
      image: litmuschaos/litmus-e2e:ci
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /etc/kubernetes:/etc/kubernetes      
    runs-on: self-hosted
    steps:
      - name: Deploy App In Cluster-1
        env:
          KUBECONFIG: /root/.kube/config
        run: make build-litmus        

      - name: Liveness In Cluster-1
        env:
          KUBECONFIG: /root/.kube/config
        run: make build-litmus        

      - name: Auxiliary App In Cluster-1
        env:
          KUBECONFIG: /root/.kube/config
        run: make build-litmus
        
  Component_Test:
    needs:
      - Setup_Litmus_Infra
      - Setup_App_Deployment   
    container: 
      image: litmuschaos/litmus-e2e:ci
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /etc/kubernetes:/etc/kubernetes
    runs-on: self-hosted
    steps:
      - name: TCID-EC2-GENERIC-OPERATOR-RECONCILE-RESILIENCY
        run: make operator-reconcile-resiliency-check
        
  App_Cleanup:
    needs:
      - Component_Test
      - Setup_App_Deployment
    container: 
      image: litmuschaos/litmus-e2e:ci
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /etc/kubernetes:/etc/kubernetes
    runs-on: self-hosted
    steps:
      - name: Application Cleanup
        run: make app-cleanup
               
  Litmus_Cleanup:
    needs:
      - App_Cleanup
      - Component_Test
      - Setup_Litmus_Infra
    container: 
      image: litmuschaos/litmus-e2e:ci
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /etc/kubernetes:/etc/kubernetes
    runs-on: self-hosted
    steps:
      - name: Application Cleanup
        run: make litmus-cleanup
               
      
