---
name: Build
on:
  push:
    branches: [master]
    
jobs:
  component-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to the Kubernetes Cluster
        run: | 
          mkdir -p ${HOME}/.kube
          echo "$CONFIG" > /home/runner/.kube/config
          chmod +x /home/runner/.kube/config
          mkdir -p /etc/kubernetes
          echo "$ADMIN_CONFIG" > /etc/kubernetes/admin.conf
          aws --version
        env:
          CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
          ADMIN_CONFIG: ${{ secrets.ADMIN_CONFIG }}
          
      - name: Getting kube config
        run: cat /home/runner/.kube/config 
          
#       - name: Setting up kubeconfig ENV for Github Chaos Action
#         run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
#         env:
#           ACTIONS_ALLOW_UNSECURE_COMMANDS: true          
        
          
      - name: Get nodes of the cluster
        run: kubectl get nodes
        
        
