---
name: Build
on:
  push:
    branches: [master]
    
jobs:
  component-pipeline:
    runs-on: self-hosted
    steps:
      - name: Getting the nodes
        run: |
          ls
          pwd
          whoami
          kubectl get nodes


  component-pipeline-2:
    runs-on: self-hosted
    steps:
      - name: Getting the nodes
        run: |
          ls
          pwd
          whoami
          kubectl get nodes
