name: Example workflow

on:
  workflow_dispatch:
jobs:
#   example:
#     name: Example Minikube-Kubernetes Cluster interaction
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: Setup Minikube
#         uses: manusa/actions-setup-minikube@v2.4.2
#         with:
#           minikube version: 'v1.16.0'
#           kubernetes version: 'v1.19.2'
#           start args: --nodes 3 -p multinode-demo --driver docker
#           github token: ${{ secrets.GITHUB_TOKEN }}
#       - name: Interact with the cluster
#         run: kubectl get nodes

  minikube-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: opsgang/ga-setup-minikube@v0.1.1
      with:
        minikube-version: 1.4.0
        k8s-version: 1.15.1
    - name: Testing
      run: |
        minikube config set vm-driver docker
        minikube config set kubernetes-version v1.15.1
        minikube start
        minikube update-context
        kubectl cluster-info
        kubectl get pods -n kube-system
  
