      #Install and configure a k3s cluster
      - name: Installing Prerequisites (K3S Cluster)
        run: |
          curl -sfL https://get.k3s.io | sh -s - --docker --write-kubeconfig-mode 664
          mkdir -p $HOME/.kube
          cp /etc/rancher/k3s/k3s.yaml $HOME/.kube/config
          kubectl wait node --all --for condition=ready --timeout=180s
          kubectl get nodes
