---
name: Namespace-Mode-Pipeline
on:
  workflow_dispatch:
    inputs:
      e2eTestImage:
        default: "litmuschaos/litmus-e2e:ci"
      goExperimentImage:
        default: "litmuschaos/go-runner:ci"
      libImage:
        default: "litmuschaos/go-runner:ci"
      operatorImage:
        default: "litmuschaos/chaos-operator:ci"
      runnerImage:
        default: "litmuschaos/chaos-runner:ci"
      chaosNamespace:
        default: "chaos"
      imagePullPolicy:
        default: "Always"
      experimentImagePullPolicy:
        default: "Always"
      chaosServiceAccount:
        default: "litmus-ns-exp-sa"

defaults:
  run:
    working-directory: /go/src

jobs:

  Pod_Delete_Namespace_Mode:
    container:
      image: "${{ github.event.inputs.e2eTestImage }}"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:rw      
      env:
        OPERATOR_IMAGE: "${{ github.event.inputs.operatorImage }}"
        RUNNER_IMAGE: "${{ github.event.inputs.runnerImage }}"
        IMAGE_PULL_POLICY: "${{ github.event.inputs.imagePullPolicy }}"
        CHAOS_NAMESPACE: "${{ github.event.inputs.chaosNamespace }}"
        APP_NS: "${{ github.event.inputs.chaosNamespace }}"
        CHAOS_SERVICE_ACCOUNT: "${{ github.event.inputs.chaosServiceAccount }}"

    runs-on: ubuntu-latest
    steps:

      #Install and configure a kind cluster
      - name: Installing Prerequisites (Kind Cluster)
        run: |
          apk add --update curl && rm -rf /var/cache/apk/*
          apk add --update docker openrc && rc-update add docker boot
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x ./kind
          cat << EOF > /tmp/cluster.yml
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          containerdConfigPatches:
          - |-
            [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry:5000"]
              endpoint = ["http://localhost:5000"]
          EOF
          export CLUSTER=$(uuidgen)
          echo "export CLUSTER=$CLUSTER" > cluster.env
          echo ./kind create cluster --name $CLUSTER --config=/tmp/cluster.yml --kubeconfig ./$CLUSTER.conf
          ./kind create cluster --name $CLUSTER --config=/tmp/cluster.yml --kubeconfig ./$CLUSTER.conf
          export KUBECONFIG=$(pwd)/$CLUSTER.conf
          kubectl get nodes 

          
      - name: Install Litmus In Namespace Mode
        run: |
          make build-litmus-ns-mode

      - name: Create nginx deployment in chaos namespace
        run: |
          kubectl create ns ${APP_NS}
          kubectl create deploy nginx --image=nginx:alpine --replicas 3 -n ${APP_NS}
          kubectl wait --for=condition=Ready pods --all --namespace ${APP_NS} --timeout=180s
          kubectl annotate deploy/nginx litmuschaos.io/chaos="true" -n ${APP_NS} --overwrite

      - name: Running Pod Delete Tests
        run: make pod-delete
