---
name: Vedant
on:
  workflow_dispatch:
  
env:
  KUBECONFIG: /root/.kube/config  

        
defaults:
  run:
    working-directory: /go/src

jobs:
  Variables_Setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Litmus Infra Setup In Cluster-1
        run: echo "Run"     
    outputs:
      e2eTestImage: "${{ secrets.EXP_IMAGE }}"
      
  ### Setup Litmus

  Setup_Litmus_Infra:
    needs: Variables_Setup  
    container:
      image: "${{ needs.Variables_Setup.outputs.e2eTestImage }}"
      volumes:
        - /home/udit/.kube:/root/.kube
        - /home/udit/.aws:/root/.aws
        - /etc/kubernetes:/etc/kubernetes

    runs-on: [self-hosted, component]
    ## Changing the working directory to image path we provided
    ## As the default path is repository checkout path.
    steps:
      - name: Litmus Infra Setup In Cluster-1
        run: |
          make build-litmus
