---
name: Pod-Level-Pipeline
on:
  schedule:
    - cron: "*/5 * * * *"
env:
  OPERATOR_IMAGE: "${{ env.operatorImage }}"
  OPERATOR_NAME: "${{ env.operatorName }}"
  RUNNER_IMAGE: "${{ env.runnerImage }}"
  IMAGE_PULL_POLICY: "${{ env.imagePullPolicy }}"
  KUBECONFIG: /root/.kube/config  

        
defaults:
  run:
    working-directory: /go/src

jobs:
  ### Setup Litmus

  Setup_Litmus_Infra:
    container:
      image: "${{ env.e2eTestImage }}"
      volumes:
        - /home/udit/.kube:/root/.kube
        - /home/udit/.aws:/root/.aws
        - /etc/kubernetes:/etc/kubernetes

    runs-on: [self-hosted, pod-level]
    ## Changing the working directory to image path we provided
    ## As the default path is repository checkout path.
    steps:
      - name: Litmus Infra Setup In Cluster-1
        run: |
          make build-litmus
