---
name: Pod-Level-Pipeline
on:
  workflow_dispatch:
  
env:
  KUBECONFIG: /root/.kube/config  

        
defaults:
  run:
    working-directory: /go/src

jobs:
  ### Setup Litmus

  Setup_Litmus_Infra:
    container:
      image: "${{ secrets.EXP_IMAGE }}"
      volumes:
        - /home/udit/.kube:/root/.kube
        - /home/udit/.aws:/root/.aws
        - /etc/kubernetes:/etc/kubernetes

    runs-on: [self-hosted, pod-level]
    ## Changing the working directory to image path we provided
    ## As the default path is repository checkout path.
    steps:
      - name: Litmus Infra Setup In Cluster-1
        run: |
          make build-litmus
